### PR TITLE
Macos support

### PR DESCRIPTION
**Pull request by LucaMoroSyn**
Hi,

I've added the macOS support as an host for LeechCore and leechcorepyc and I thought you might be interested.
Most of the Linux code was already working as is and I only had to change some functions and Makefiles.

Another PR will follow-up for the ft601 driver support.

I'm not really familiar with the project so let me know if you need some adjustments.

Thanks for this project !

### CODE REVIEW

**Comment by ufrisk** [comment]
Thank you for this very nice contribution :)

Having mac support is something I've been asked about before but it's not something I've prioritized for various reasons. Mostly because I'm not very familiar with the platform as such and that I've not been too keen on adding a lot of testing time for all new releases by officially supporting it.

I've put a lot of time into my tools and this is one of the very few meaningful pull requests I've gotten. I'm however not able to accept the pull request as is into my core project (plugin project is completely ok). I mention this in the readme (asking to contact me before making contributions to the core project). Reason being that I have the need to be able to dual-license. I'm not able to bind myself fully by the GPLv3 for this contribution.

The solution for this is to add some kind of contributors license agreement (CLA). Something akin to the [Ubuntu CLA](https://assets.ubuntu.com/v1/ff2478d1-Canonical-HA-CLA-ANY-I_v1.2.pdf). But I would need to look into this if we decide to go in this direction.

Please understand that even after accepting the pull request I'd be hesitant to fully support the mac version with official binary builds and testing (even though it would build just fine).

I don't know if this CLA stuff would be of interest / acceptable. If not I totally understand. Regardless I'd be super happy to link to your macOS port should you so like.

Ulf

**Comment by LucaMoroSyn** [comment]
Hi,

Thanks for your reply!

I totally get your position and understand that an official support of macOS would add some hassles the project does not need.

These patches came from a bit of tinkering on my side and I proposed the PR without taking into consideration the readme and contribution guidelines.

So I accept the refusal of the PR without any problem.

> Regardless I'd be super happy to link to your macOS port should you so like.

I guess I'll keep the port on my github for anyone interested (unless you don't want to).
However I'm unsure that I'll maintain it updated.
So it's better if you don't link it.

Thanks again for this project!

**Comment by ufrisk** [comment]
Thanks for understanding.

If you would consider me allow to link to your macOS port just please let me know and I'll add it to the readme. This would be useful to people still; I know you're not the only one wishing this to run on macOS.

**Comment by LucaMoroSyn** [comment]
> If you would consider me allow to link to your macOS port just please let me know and I'll add it to the readme. This would be useful to people still; I know you're not the only one wishing this to run on macOS.

Sure! As I said I'm not sure I'll maintain it in the future but if you think it might be useful for others feel free to link it.
Thanks.

**Pull request closed without merging**
