### PR TITLE
Fix error in leechcore.h comment

### PR DESCRIPTION
**Pull request by slack2450**
I know it's minor I just thought I'd point it out and submit a quick pull request. If I've misunderstood what it should be please let me know

### CODE REVIEW

**Comment by ufrisk** [comment]
Thanks for pointing this one out. It's clear that I messed things up.

I've been very cautious about merging code changes due top copyright reasons though. I wish to be able to provide alternative licenses to others should they be interested, and by merging code changes to the core parts of the project I might not be able to do that without some kind of contributor agreement set up, which just is too much hassle for a pull request like this.

But many thanks for pointing out my errors. Thanks and please let me know should you find something else 👍

**Comment by slack2450** [comment]
Okay I understand makes sense!

**Comment by slack2450** [comment]
Hey @ufrisk just a bump, noticed this typo is still sitting there. Sure you've got more important things to look at to be fair.

**Comment by ufrisk** [comment]
I've fixed quite a few spelling and indentation issues in the most recent header file, so I hope this should now be resolved. Many thanks for pointing this out to me 👍

**Pull request closed without merging**
